# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: crservice@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
from distutils.core import setup
setup(
  name = 'swagger-client',
  packages = ['swagger-client'],
  version = '1.0.0',
  license='MIT',
  description = 'Speech Services API v2.0',
  author = 'Santosh Kumar',
  author_email = 'san.19884u@gmail.com',
  url = 'https://github.com/SantoshML/python-client',
  download_url = 'https://github.com/SantoshML/python-client/archive/v1.0.tar.gz',
  keywords = ['Batch', 'transcription', 'pyton', 'Rest API',"Swagger", "Speech Services API v2.0"],
  install_requires=[
      "certifi>=2017.4.17",
      "python-dateutil>=2.1",
      "six>=1.10",
      "urllib3>=1.23"
  ],
  classifiers=[  # Optional
    # How mature is this project? Common values are
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable
    'Development Status :: 3 - Alpha',

    # Indicate who your project is intended for
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',

    # Pick your license as you wish
    'License :: OSI Approved :: MIT License',

    # Specify the Python versions you support here. In particular, ensure
    # that you indicate whether you support Python 2, Python 3 or both.
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
  ],
)
